
networks:
  yoga_net:

services:
  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from multiplayer.yoga --to app:5000
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - yoga_net

  app:
    build: .
    container_name: app
    env_file: .env
    depends_on:
      - db
    entrypoint: npm run start
    networks:
      - yoga_net

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - yoga_net

volumes:
  pgdata:
  caddy_data:
  caddy_config: