
services:

  app:
    image: ghcr.io/insanity54/flowworld:latest
    env_file: .env
    depends_on:
      - db
    entrypoint: npm run start


  db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: