services:
  flowworld:
    build:
      context: .
      dockerfile: production.Dockerfile
    image: ghcr.io/insanity54/flowworld
    ports:
      - "8095:8095"
    env_file:
      - .env.production.local
