services:
  flowworld:
    build:
      context: .
      dockerfile: development.Dockerfile
    image: ghcr.io/insanity54/flowworld
    ports:
      - "8095:8095"
    env_file:
      - .env.development.local
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./package.json:/app/package.json
      - ./svelte.config.js:/app/svelte.config.js
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
