replicaCount: 1

image:
  repository: ghcr.io/insanity54/flowworld
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext:
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8095

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: flowworld.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

command: []
args: []

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
  accessMode: ReadWriteOnce
  mountPath: /app/data

extraArgs: []
  # - --dev

env: {}
  # POSE_INTERVAL: "42000"

envFromSecret: ""
  # name of a pre-existing Secret to use as env source

nodeSelector: {}
tolerations: []
affinity: {}
